--!strict
-- CombatShared.lua
-- Shared constants and utility functions for ZEN Reborn combat system.
-- Author: Generated by ChatGPT

local CombatShared = {}

-- Animation asset catalogue. Replace the asset IDs with your exported animation ids.
CombatShared.Animations = {
    Idle = "rbxassetid://0", -- Placeholder, assign in Studio
    Walk = "rbxassetid://0",
    Run = "rbxassetid://0",
    AttackLight = "rbxassetid://0",
    Block = "rbxassetid://0",
    Shockwave = "rbxassetid://0",
    Kick = "rbxassetid://0",
    Taunt = "rbxassetid://0",
    EmoteHold = "rbxassetid://0",
}

CombatShared.Config = {
    LockOnRange = 120,
    AttackRange = 14,
    AttackDamage = 18,
    ShockwaveDamage = 26,
    ShockwaveRadius = 20,
    KickDamage = 8,
    BlockDamageScalar = 0.3,
    BlockBreakThreshold = 2.5, -- seconds of continuous blocking before the kick breaks it
    KickCooldown = 4,
    ShockwaveCooldown = 6,
    TauntCooldown = 5,
    RunSpeed = 24,
    WalkSpeed = 14,
    BlockWalkSpeed = 8,
}

function CombatShared.FindClosestEnemy(player: Player, range: number): Player?
    local Players = game:GetService("Players")
    local bestPlayer: Player? = nil
    local bestDistance = range

    for _, other in Players:GetPlayers() do
        if other ~= player then
            local character = other.Character
            if character then
                local hrp = character:FindFirstChild("HumanoidRootPart")
                local humanoid = character:FindFirstChildOfClass("Humanoid")
                if hrp and humanoid and humanoid.Health > 0 then
                    local primary = player.Character and player.Character:FindFirstChild("HumanoidRootPart")
                    if primary then
                        local distance = (hrp.Position - primary.Position).Magnitude
                        if distance < bestDistance then
                            bestDistance = distance
                            bestPlayer = other
                        end
                    end
                end
            end
        end
    end

    return bestPlayer
end

return CombatShared
